source "https://rubygems.org"

ruby '~> 2.7.0'

gem "aws-sdk-ssm"
gem "aws-sdk-sqs"
gem "aws-sdk-dynamodb"
gem "ruby-openai"
gem "awesome_print"
gem "activesupport"
gem "slack-ruby-client"
gem "pry"

group :test do
  gem "rake"
  gem "guard"
  gem "guard-rake"
  gem "rspec"
  gem "rspec-mocks"
  gem 'webmock'
  gem 'simplecov', require: false
  gem "pry"
  gem "byebug"
end
